steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/my-docker-repo/psec-nodejs-skeleton-image', '.' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/my-docker-repo/psec-nodejs-skeleton-image']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
    - '-c'
    - > 
      gcloud deploy releases create release-$BUILD_ID
      --delivery-pipeline=psec-nodejs-skeleton
      --region=us-central1
      --images=my-app-image=us-central1-docker.pkg.dev/$PROJECT_ID/my-docker-repo/psec-nodejs-skeleton-image
      --source=./