apiVersion: apps/v1
kind: Deployment
metadata:
  name: psec-nodejs-skeleton
spec:
  replicas: 1
  selector:
    matchLabels:
      app: psec-nodejs-skeleton
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: psec-nodejs-skeleton
    spec:
      containers:
      - name: psec-nodejs-skeleton
        image: my-app-image
        ports:
          - containerPort: 80